import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {Miniflare} from 'miniflare';
import {validDateTime,isAdmin} from '../worker/index.js';
const origin='http://localhost';
const adminHeaders={'oai-authenticated-user-email':'owner@aura.test',origin};
const guestHeaders={origin};
let mf,db;
test.before(async()=>{mf=new Miniflare({modules:true,script:readFileSync('dist/server/index.js','utf8'),compatibilityDate:'2024-12-01',d1Databases:{DB:'aura-test'},r2Buckets:['BUCKET'],bindings:{ADMIN_EMAILS:'owner@aura.test'}});db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();});
test.after(async()=>{await mf?.dispose();});
async function request(path,{method='GET',body,admin=false,headers={}}={}){const init={method,redirect:'manual',headers:{...(admin?adminHeaders:guestHeaders),...headers}};if(body!==undefined){init.body=JSON.stringify(body);init.headers['Content-Type']='application/json';}return mf.dispatchFetch(origin+path,init);}
async function data(path,options){const response=await request(path,options);return {status:response.status,body:await response.json()};}
async function slot(start,end,service='studio'){const result=await data('/api/admin/slots',{method:'POST',admin:true,body:{service,start,end}});assert.equal(result.status,201,JSON.stringify(result.body));return result.body.id;}
const bookingInput=slotId=>({slotId,name:'Test Customer',email:'customer@example.test',phone:'+48 123456789',message:'Portrait test',consent:true});
test('admin authorization, CSRF and hidden admin document',async()=>{assert.equal((await request('/api/admin/dashboard')).status,403);assert.equal((await request('/admin')).status,302);assert.equal((await request('/admin',{admin:true})).status,200);assert.equal((await request('/admin.html')).status,404);assert.equal((await request('/api/admin/dashboard',{headers:{'oai-authenticated-user-email':'outsider@test.example'}})).status,403);assert.equal((await request('/api/admin/settings',{method:'PUT',admin:true,headers:{origin:'https://attacker.test'},body:{}})).status,403);assert.equal(isAdmin(new Request('https://production.test/admin'),{LOCAL_DEV:'1'}),false);});
test('actual database migration, content persistence and public privacy',async()=>{const updated=await data('/api/admin/settings',{method:'PUT',admin:true,body:{heroPl:'Test studio',heroEn:'Test studio',rentalPrice:'150 zł / hour',equipmentPl:'Test softbox',equipmentEn:'Test softbox'}});assert.equal(updated.status,200);const c=await data('/api/studio');assert.equal(c.body.settings.rentalPrice,'150 zł / hour');assert.equal(c.body.settings.heroPl,'Test studio');assert.equal(c.body.bookings,undefined);assert.equal(c.body.admin,undefined);assert.equal(c.body.settings.ADMIN_EMAILS,undefined);});
test('slot validation, overlap prevention, state controls and availability',async()=>{assert.equal(validDateTime('2099-02-30T10:00'),false);assert.equal((await data('/api/admin/slots',{method:'POST',admin:true,body:{service:'studio',start:'2020-01-01T10:00',end:'2020-01-01T11:00'}})).status,400);const id=await slot('2099-01-01T10:00','2099-01-01T11:00');assert.equal((await data('/api/admin/slots',{method:'POST',admin:true,body:{service:'session',start:'2099-01-01T10:30',end:'2099-01-01T11:30'}})).status,409);assert((await data('/api/availability?service=studio')).body.slots.some(s=>s.id===id));assert.equal((await data('/api/admin/slots/'+id,{method:'PATCH',admin:true,body:{state:'blocked'}})).status,200);assert(!(await data('/api/availability')).body.slots.some(s=>s.id===id));assert.equal((await data('/api/admin/slots/'+id,{method:'PATCH',admin:true,body:{state:'open'}})).status,200);});
test('concurrent booking requests cannot reserve the same slot twice',async()=>{const id=await slot('2099-01-02T10:00','2099-01-02T11:00');const results=await Promise.all([data('/api/bookings',{method:'POST',body:bookingInput(id)}),data('/api/bookings',{method:'POST',body:bookingInput(id)})]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);const success=results.find(r=>r.status===201);assert.match(success.body.reference,/^AURA-[A-F0-9]{10}$/);assert.equal(success.body.status,'pending');assert(!(await data('/api/availability')).body.slots.some(s=>s.id===id));const admin=await data('/api/admin/dashboard',{admin:true});const b=admin.body.bookings.find(b=>b.reference===success.body.reference);assert.equal(b.email,'customer@example.test');assert.equal((await data('/api/admin/slots/'+id,{method:'PATCH',admin:true,body:{state:'blocked'}})).status,409);assert.equal((await data('/api/admin/bookings/'+b.id,{method:'PATCH',admin:true,body:{status:'confirmed'}})).status,200);assert.equal((await data('/api/admin/bookings/'+b.id,{method:'PATCH',admin:true,body:{status:'cancelled'}})).status,200);assert((await data('/api/availability')).body.slots.some(s=>s.id===id));assert.equal((await data('/api/admin/bookings/'+b.id,{method:'PATCH',admin:true,body:{status:'confirmed'}})).status,409);});
test('invalid booking details and foreign-origin writes are rejected',async()=>{const id=await slot('2099-01-03T10:00','2099-01-03T11:00');assert.equal((await data('/api/bookings',{method:'POST',body:{...bookingInput(id),email:'bad'}})).status,400);assert.equal((await data('/api/bookings',{method:'POST',body:{...bookingInput(id),consent:false}})).status,400);assert.equal((await data('/api/bookings',{method:'POST',headers:{origin:'https://attacker.test'},body:bookingInput(id)})).status,403);assert.equal((await data('/api/bookings',{method:'POST',body:{...bookingInput(id),website:'spam'}})).status,400);});
test('photo uploads persist in R2 and can be assigned and removed',async()=>{const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=','base64');const response=await mf.dispatchFetch(origin+'/api/admin/photos?category=studio&captionPl=Studio&captionEn=Studio',{method:'POST',headers:adminHeaders,body:png});assert.equal(response.status,201);const photo=await response.json();const media=await request(photo.url);assert.equal(media.status,200);assert.equal(media.headers.get('content-type'),'image/png');assert.equal((await media.arrayBuffer()).byteLength,png.length);assert.equal((await data('/api/admin/settings',{method:'PUT',admin:true,body:{heroPhoto:photo.id}})).status,200);assert.equal((await data('/api/studio')).body.settings.heroPhoto,photo.id);assert.equal((await data('/api/admin/photos/'+photo.id,{method:'DELETE',admin:true})).status,200);assert.equal((await request(photo.url)).status,404);assert.equal((await data('/api/studio')).body.settings.heroPhoto,'');const bad=await mf.dispatchFetch(origin+'/api/admin/photos?category=studio&captionPl=Studio&captionEn=Studio',{method:'POST',headers:adminHeaders,body:'<svg onload="alert(1)"></svg>'});assert.equal(bad.status,400);});
test('backend assistant uses saved studio information and current availability',async()=>{await data('/api/admin/settings',{method:'PUT',admin:true,body:{rentalPrice:'200 zł / hour',equipmentEn:'A verified softbox'}});const price=await data('/api/chat',{method:'POST',body:{message:'pricing',language:'en'}});assert.equal(price.status,200);assert.match(price.body.reply,/200 zł/);const equipment=await data('/api/chat',{method:'POST',body:{message:'equipment',language:'en'}});assert.equal(equipment.body.reply,'A verified softbox');const availability=await data('/api/chat',{method:'POST',body:{message:'booking',language:'en'}});assert.match(availability.body.reply,/slots available/);assert.equal(availability.body.kind,'studio-faq');});
test('backend rate limits booking spam',async()=>{const responses=[];for(let i=0;i<10;i++)responses.push((await data('/api/bookings',{method:'POST',body:{}})).status);assert(responses.includes(429));});
test('frontend assets, anchor targets and security headers',async()=>{for(const file of ['index.html','admin.html']){const html=readFileSync('public/'+file,'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'duplicate IDs');for(const match of html.matchAll(/href="#([^"]+)"/g))assert(ids.includes(match[1]),'missing anchor '+match[1]);const js=readFileSync('public/'+(file==='index.html'?'app.js':'admin.js'),'utf8');for(const match of js.matchAll(/\$\('([^']+)'\)/g))assert(ids.includes(match[1]),'missing JS element '+match[1]);assert(!html.includes('<span</span>'));}const home=await request('/');assert.equal(home.status,200);assert.match(home.headers.get('content-security-policy'),/script-src 'self'/);assert.equal((await request('/app.js')).status,200);assert.equal((await request('/admin.js')).status,200);});
