import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync,readdirSync} from 'node:fs';
import {parseHTML} from 'linkedom';
import {Miniflare} from 'miniflare';
let mf;
const origin='http://localhost';
async function backend(path,{method='GET',body,admin=false}={}){return mf.dispatchFetch(origin+path,{method,redirect:'manual',headers:{origin,'Content-Type':'application/json',...(admin?{'oai-authenticated-user-email':'owner@aura.test'}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}
async function waitFor(check,label){for(let i=0;i<150;i++){if(check())return;await new Promise(r=>setTimeout(r,20));}throw Error('Timed out: '+label);}
function browser(file,admin=false){const {window,document}=parseHTML(readFileSync('public/'+file+'.html','utf8'));Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return Array.from(this.options).find(o=>o.selected)?.getAttribute('value')??this.options[0]?.getAttribute('value')??'';},set(value){for(const option of this.options)option.selected=option.getAttribute('value')===String(value);}});for(const el of document.querySelectorAll('*')){el.focus=()=>{};el.scrollIntoView=()=>{};}for(const form of document.querySelectorAll('form')){form.reportValidity=()=>true;form.reset=()=>{for(const input of form.querySelectorAll('input,textarea')){input.value='';input.checked=false;}};}for(const dialog of document.querySelectorAll('dialog')){dialog.showModal=()=>{dialog.open=true;};dialog.close=()=>{dialog.open=false;dialog.dispatchEvent(new window.Event('close'));};}window.open=()=>{};const location={hash:'',reload(){}};const context=vm.createContext({window,document,location,console,URL,URLSearchParams,Intl,Date,TextEncoder,setTimeout,clearTimeout,matchMedia:()=>({matches:true}),fetch:(path,init={})=>mf.dispatchFetch(origin+path,{...init,headers:{...init.headers,origin,...(admin?{'oai-authenticated-user-email':'owner@aura.test'}:{})}})});vm.runInContext(readFileSync('public/'+(file==='index'?'app':'admin')+'.js','utf8'),context);return {window,document,$:id=>document.getElementById(id),context};}
function submit(browser,id){const form=browser.$(id),event=new browser.window.Event('submit',{bubbles:true,cancelable:true});event.submitter=form.querySelector('button[type="submit"]');form.dispatchEvent(event);}
test.before(async()=>{mf=new Miniflare({modules:true,script:readFileSync('dist/server/index.js','utf8'),compatibilityDate:'2024-12-01',d1Databases:{DB:'aura-dom-test'},r2Buckets:['BUCKET'],bindings:{ADMIN_EMAILS:'owner@aura.test'}});const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();await backend('/api/admin/slots',{method:'POST',admin:true,body:{service:'studio',start:'2099-05-01T10:00',end:'2099-05-01T11:00'}});});
test.after(async()=>await mf?.dispose());
test('visitor selects a real slot and saves a booking through the frontend',async()=>{const page=browser('index');await waitFor(()=>!page.$('date').disabled,'availability loaded');page.$('language').click();assert.equal(page.document.documentElement.lang,'en');page.$('date').value='2099-05-01';page.$('date').dispatchEvent(new page.window.Event('change'));assert.equal(page.$('slot').options.length,2);page.$('slot').value=page.$('slot').options[1].value;page.$('slot').dispatchEvent(new page.window.Event('change'));assert.equal(page.$('booking-submit').disabled,false);page.$('name').value='Frontend Customer';page.$('email').value='frontend@example.test';page.$('consent').checked=true;page.$('project').value='A session from the frontend';submit(page,'booking-form');await waitFor(()=>!page.$('booking-success').hidden,'booking saved');assert.match(page.$('booking-reference').textContent,/AURA-/);const dashboard=await (await backend('/api/admin/dashboard',{admin:true})).json();assert.equal(dashboard.bookings[0].name,'Frontend Customer');page.document.querySelector('[data-filter="session"]').click();assert.equal(page.$('gallery-grid').children.length,1);page.$('chat-toggle').click();page.$('chat-input').value='equipment';submit(page,'chat-form');await waitFor(()=>page.$('chat-log').children.length>=3,'assistant response');assert.match(page.$('chat-log').textContent,/Equipment is confirmed/);await waitFor(()=>page.$('booking-submit').disabled,'held slot removed');});
test('admin can confirm a booking and save edited studio content',async()=>{const page=browser('admin',true);await waitFor(()=>page.$('booking-list').children.length&&page.$('metric-pending').textContent==='1','admin data loaded');const confirm=Array.from(page.$('booking-list').querySelectorAll('button')).find(b=>b.textContent==='Confirm booking');assert(confirm);confirm.click();await waitFor(()=>page.$('confirm-dialog').open,'confirm dialog');page.$('confirm-dialog').returnValue='confirm';page.$('confirm-dialog').close();await waitFor(()=>page.$('metric-confirmed').textContent==='1','booking confirmed');page.document.querySelector('[data-tab="content"]').click();assert.equal(page.$('tab-content').hidden,false);page.$('content-address').value='Studio test address';page.$('content-equipmentEn').value='Verified studio equipment';submit(page,'content-form');await waitFor(()=>page.$('dashboard-status').textContent==='Studio content saved.','content saved');const result=await (await backend('/api/studio')).json();assert.equal(result.settings.address,'Studio test address');assert.equal(result.settings.equipmentEn,'Verified studio equipment');});
test('language switching treats saved studio copy as text, not HTML',async()=>{await backend('/api/admin/settings',{method:'PUT',admin:true,body:{heroPl:'<img src=x onerror=alert(1)><br>Studio',heroEn:'Safe studio'}});const page=browser('index');await waitFor(()=>page.document.querySelector('.hero h1 span').textContent.includes('<img'),'studio copy loaded');page.$('language').click();page.$('language').click();assert.equal(page.document.querySelector('.hero h1 img'),null);assert.match(page.document.querySelector('.hero h1 span').textContent,/<img/);});
