import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync,readdirSync} from 'node:fs';
import {parseHTML} from 'linkedom';
import {Miniflare} from 'miniflare';
let mf;
const origin='http://localhost';
async function backend(path,{method='GET',body,admin=false}={}){return mf.dispatchFetch(origin+path,{method,redirect:'manual',headers:{origin,'Content-Type':'application/json',...(admin?{'oai-authenticated-user-email':'owner@aura.test'}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}
async function waitFor(check,label){for(let i=0;i<150;i++){if(check())return;await new Promise(r=>setTimeout(r,20));}throw Error('Timed out: '+label);}
function browser(file,admin=false){const {window,document}=parseHTML(readFileSync('public/'+file+'.html','utf8'));Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return Array.from(this.options).find(o=>o.selected)?.getAttribute('value')??this.options[0]?.getAttribute('value')??'';},set(value){for(const option of this.options){if(option.getAttribute('value')===String(value))option.setAttribute('selected','');else option.removeAttribute('selected');}}});for(const el of document.querySelectorAll('*')){el.focus=()=>{};el.scrollIntoView=()=>{};}for(const form of document.querySelectorAll('form')){form.reportValidity=()=>true;form.reset=()=>{for(const input of form.querySelectorAll('input,textarea')){input.value='';input.checked=false;}};}for(const dialog of document.querySelectorAll('dialog')){dialog.showModal=()=>{dialog.open=true;};dialog.close=()=>{dialog.open=false;dialog.dispatchEvent(new window.Event('close'));};}window.open=()=>{};const location={hash:'',reload(){}};const context=vm.createContext({window,document,location,console,URL,URLSearchParams,Intl,Date,TextEncoder,setTimeout,clearTimeout,matchMedia:()=>({matches:true}),fetch:(path,init={})=>mf.dispatchFetch(origin+path,{...init,headers:{...init.headers,origin,...(admin?{'oai-authenticated-user-email':'owner@aura.test'}:{})}})});vm.runInContext(readFileSync('public/'+(file==='admin'?'admin':'app')+'.js','utf8'),context);return {window,document,$:id=>document.getElementById(id),context};}
function submit(browser,id){const form=browser.$(id),event=new browser.window.Event('submit',{bubbles:true,cancelable:true});event.submitter=form.querySelector('button[type="submit"]');form.dispatchEvent(event);}
test.before(async()=>{mf=new Miniflare({modules:true,script:readFileSync('dist/server/index.js','utf8'),compatibilityDate:'2024-12-01',d1Databases:{DB:'aura-dom-test'},r2Buckets:['BUCKET'],bindings:{ADMIN_EMAILS:'owner@aura.test'}});const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();await backend('/api/admin/slots',{method:'POST',admin:true,body:{service:'studio',start:'2099-05-01T10:00',end:'2099-05-01T11:00'}});});
test.after(async()=>await mf?.dispose());
test('visitor books a nine-hour rental with live pricing and sees the held time',async()=>{
 const page=browser('index');await waitFor(()=>!page.$('date').disabled,'calendar loaded');page.$('language').click();assert.equal(page.document.documentElement.lang,'en');
 for(const [caption,src] of [['Room to recharge','/assets/studio-lounge.jpg'],['Colour and light','/assets/orange-backdrop.jpg'],['The green space','/assets/green-studio.jpg']]){const img=Array.from(page.$('gallery-grid').querySelectorAll('img')).find(image=>image.alt===caption);assert(img);assert.equal(img.getAttribute('src'),src);assert.equal(img.hidden,false);}
 page.$('calendar-next').click();await waitFor(()=>!page.$('date').disabled,'next month loaded');const day=page.document.querySelector('.calendar-day:not([disabled])');const date=day.dataset.date;day.click();assert.equal(page.$('date').value,date);
 page.$('duration').value='540';page.$('duration').dispatchEvent(new page.window.Event('change'));assert.match(page.$('booking-summary').textContent,/1350 PLN/);const start=page.document.querySelector('[data-start="'+date+'T10:00"]');assert.equal(start.disabled,false);start.click();assert.equal(page.document.querySelector('[data-start="'+date+'T10:00"]').getAttribute('aria-pressed'),'true');assert.match(page.$('booking-summary').textContent,/10:00 - 19:00/);assert.equal(page.$('booking-submit').disabled,false);
 page.$('name').value='Frontend Customer';page.$('email').value='frontend@example.test';page.$('consent').checked=true;page.$('project').value='Nine-hour rental';submit(page,'booking-form');await waitFor(()=>!page.$('booking-success').hidden,'booking saved');assert.match(page.$('booking-reference').textContent,/1350 PLN/);await waitFor(()=>!page.$('date').disabled,'calendar refreshed');
 const busy=page.document.querySelector('[data-start="'+date+'T10:00"]');assert.equal(busy.disabled,true);assert(busy.classList.contains('booked'));assert.equal(page.$('booking-submit').disabled,true);
 const dashboard=await (await backend('/api/admin/dashboard',{admin:true})).json();assert.equal(dashboard.bookings[0].name,'Frontend Customer');assert.equal(dashboard.bookings[0].durationMinutes,540);assert.equal(dashboard.bookings[0].totalPln,1350);
 page.document.querySelector('[data-filter="session"]').click();assert.equal(page.$('gallery-grid').children.length,1);page.$('chat-toggle').click();page.$('chat-input').value='equipment';submit(page,'chat-form');await waitFor(()=>page.$('chat-log').children.length>=3,'assistant response');assert.match(page.$('chat-log').textContent,/Equipment is confirmed/);
});
test('admin can confirm a booking and save edited studio content',async()=>{const page=browser('admin',true);await waitFor(()=>page.$('booking-list').children.length&&page.$('metric-pending').textContent==='1','admin data loaded');const confirm=Array.from(page.$('booking-list').querySelectorAll('button')).find(b=>b.textContent==='Confirm booking');assert(confirm);confirm.click();await waitFor(()=>page.$('confirm-dialog').open,'confirm dialog');page.$('confirm-dialog').returnValue='confirm';page.$('confirm-dialog').close();await waitFor(()=>page.$('metric-confirmed').textContent==='1','booking confirmed');page.document.querySelector('[data-tab="content"]').click();assert.equal(page.$('tab-content').hidden,false);page.$('content-address').value='Studio test address';page.$('content-equipmentEn').value='Verified studio equipment';submit(page,'content-form');await waitFor(()=>page.$('dashboard-status').textContent==='Studio content saved.','content saved');const result=await (await backend('/api/studio')).json();assert.equal(result.settings.address,'Studio test address');assert.equal(result.settings.equipmentEn,'Verified studio equipment');});
test('language switching treats saved studio copy as text, not HTML',async()=>{await backend('/api/admin/settings',{method:'PUT',admin:true,body:{heroPl:'<img src=x onerror=alert(1)><br>Studio',heroEn:'Safe studio'}});const page=browser('index');await waitFor(()=>page.document.querySelector('.hero h1 span').textContent.includes('<img'),'studio copy loaded');page.$('language').click();page.$('language').click();assert.equal(page.document.querySelector('.hero h1 img'),null);assert.match(page.document.querySelector('.hero h1 span').textContent,/<img/);});

test('dedicated booking page offers thirty-minute and one-hour photography with correct prices',async()=>{
 for(const path of ['/booking','/booking/']){const response=await backend(path);assert.equal(response.status,200);assert.match(await response.text(),/class="booking-page"/);}
 const page=browser('booking');await waitFor(()=>!page.$('date').disabled,'calendar loaded');page.$('language').click();page.$('service').value='session';page.$('service').dispatchEvent(new page.window.Event('change'));await waitFor(()=>!page.$('date').disabled,'session calendar');assert.deepEqual(Array.from(page.$('duration').options).map(o=>o.value),['30','60']);assert.match(page.$('booking-summary').textContent,/150 PLN/);
 page.$('calendar-next').click();await waitFor(()=>!page.$('date').disabled,'next month');const day=page.document.querySelector('.calendar-day:not([disabled])');day.click();const date=day.dataset.date;page.document.querySelector('[data-start="'+date+'T09:30"]').click();assert.match(page.$('booking-summary').textContent,/09:30 - 10:00/);assert.equal(page.$('booking-submit').disabled,false);
 page.$('duration').value='60';page.$('duration').dispatchEvent(new page.window.Event('change'));assert.match(page.$('booking-summary').textContent,/250 PLN/);assert.equal(page.$('booking-submit').disabled,true,'Longer session overlaps the existing rental and clears the time');page.document.querySelector('[data-start="'+date+'T08:30"]').click();assert.match(page.$('booking-summary').textContent,/08:30 - 09:30/);assert.equal(page.document.querySelector('.hero'),null);
});
