// Database and object storage bindings are supplied by Sites in production.
// Frontend assets are embedded by scripts/build.mjs; no secrets enter browser code.
export const defaults = {
 name:'Aura Studio Warsaw', instagram:'https://www.instagram.com/aura.studiowarsaw/',
 address:'', email:'', phone:'',
 heroPl:'Twój pomysł.', heroEn:'Your vision.', subtitlePl:'Nasza przestrzeń.', subtitleEn:'Our space.',
 descriptionPl:'Miejsce na światło, pomysły i kadry, które zostają. Poznaj Aura Studio Warsaw.', descriptionEn:'Room for light, ideas, and images that stay with you. Discover Aura Studio Warsaw.',
 studioPl:'Planujesz sesję, kampanię lub własny projekt? Opowiedz nam o swojej wizji. Ustalimy, jak najlepiej przygotować studio do Twojej pracy.', studioEn:'Planning a shoot, a campaign, or a personal project? Tell us your vision. Together, we will prepare the studio for your shoot.',
 equipmentPl:'Wyposażenie potwierdzamy przed rezerwacją.', equipmentEn:'Equipment is confirmed before booking.',
 policyPl:'Rezerwacja wymaga potwierdzenia przez studio. Zapytaj o cenę i warunki anulowania przed potwierdzeniem.', policyEn:'Bookings require studio approval. Confirm pricing and cancellation terms before your booking is confirmed.',
 rentalPrice:'',sessionPrice:'',heroPhoto:'',studioPhoto:''
};
const securityHeaders={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob:; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com"};
class HttpError extends Error { constructor(status,message){super(message);this.status=status;} }
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{...securityHeaders,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const clean=(value,max=2000)=>typeof value==='string'?value.trim().slice(0,max):'';
const bookingStates=new Set(['pending','confirmed','rejected','cancelled']);
export function warsawNow(){const p=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date());return p.replace(' ','T');}
export function validDateTime(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))return false;const d=new Date(value+'Z');return !Number.isNaN(d.valueOf())&&d.toISOString().slice(0,16)===value;}
export function identity(request,env){
 const host=new URL(request.url).hostname;
 if(env.LOCAL_DEV==='1'&&['localhost','127.0.0.1'].includes(host))return 'local@aura.test';
 return request.headers.get('oai-authenticated-user-email')?.toLowerCase()||'';
}
export function isAdmin(request,env){const who=identity(request,env);if(env.LOCAL_DEV==='1'&&who==='local@aura.test')return true;return !!who&&String(env.ADMIN_EMAILS||'').toLowerCase().split(',').map(s=>s.trim()).includes(who);}
function requireAdmin(request,env){if(!isAdmin(request,env))throw new HttpError(403,'Administrator access required.');}
function requireSameOrigin(request){const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)throw new HttpError(403,'Invalid request origin.');}
function requireDB(env){if(!env.DB)throw new HttpError(503,'Studio service temporarily unavailable. Please try again.');return env.DB;}
async function body(request,max=10000){if(Number(request.headers.get('content-length')||0)>max)throw new HttpError(413,'Request too large.');const raw=await readLimited(request,max);try{return JSON.parse(new TextDecoder().decode(raw));}catch{throw new HttpError(400,'Invalid request.');}}
async function readLimited(request,max){const reader=request.body?.getReader();if(!reader)return new Uint8Array();let length=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();throw new HttpError(413,'Request too large.');}chunks.push(value);}const result=new Uint8Array(length);let offset=0;for(const c of chunks){result.set(c,offset);offset+=c.length;}return result;}
async function config(db){const row=await db.prepare('SELECT value FROM settings WHERE key = ?').bind('studio').first();if(!row)return {...defaults};try{return {...defaults,...JSON.parse(row.value)};}catch{throw new HttpError(503,'Studio content temporarily unavailable.');}}
async function throttle(request,db,group,limit){const raw=request.headers.get('cf-connecting-ip')||identity(request,{})||'anonymous';const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));const key=group+':'+Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('');const window=Math.floor(Date.now()/600000);const row=await db.prepare('INSERT INTO rate_limits (key, window_start, count) VALUES (?, ?, 1) ON CONFLICT(key) DO UPDATE SET count = CASE WHEN window_start = excluded.window_start THEN count + 1 ELSE 1 END, window_start = excluded.window_start RETURNING count').bind(key,window).first();if(row.count>limit)throw new HttpError(429,'Too many requests. Please try again later.');}
function normalizeSettings(input){const out={};for(const [key,value] of Object.entries(defaults)){out[key]=clean(input[key]??value,2000);}if(out.instagram!=='https://www.instagram.com/aura.studiowarsaw/')throw new HttpError(400,'Use the Aura Studio Warsaw Instagram URL.');if(out.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out.email))throw new HttpError(400,'Invalid contact email.');return out;}
async function available(db,service,date){const now=warsawNow();let query=`SELECT s.id, s.service, s.start, s.end FROM slots s WHERE s.state = 'open' AND s.start > ? AND NOT EXISTS (SELECT 1 FROM bookings b JOIN slots held ON b.slot_id = held.id WHERE b.status IN ('pending','confirmed') AND held.start < s.end AND held.end > s.start)`;const args=[now];if(service){query+=' AND s.service = ?';args.push(service);}if(date){query+=' AND substr(s.start, 1, 10) = ?';args.push(date);}query+=' ORDER BY s.start LIMIT 200';return (await db.prepare(query).bind(...args).all()).results;}
async function createBooking(request,db){await throttle(request,db,'booking',8);const input=await body(request);if(clean(input.website))throw new HttpError(400,'Invalid request.');const name=clean(input.name,100),email=clean(input.email,254).toLowerCase(),phone=clean(input.phone,40),message=clean(input.message,2000),slotId=clean(input.slotId,100);if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||!slotId||input.consent!==true)throw new HttpError(400,'Enter your name, valid email, slot and contact consent.');const slot=await db.prepare('SELECT * FROM slots WHERE id = ?').bind(slotId).first();if(!slot||slot.state!=='open'||slot.start<=warsawNow())throw new HttpError(409,'This slot is no longer available. Please choose another.');const id=crypto.randomUUID(),reference='AURA-'+crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase(),now=new Date().toISOString();let result;try{result=await db.prepare(`INSERT INTO bookings (id, reference, slot_id, name, email, phone, message, status, created_at, updated_at) SELECT ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ? WHERE EXISTS (SELECT 1 FROM slots s WHERE s.id = ? AND s.state = 'open' AND s.start > ?) AND NOT EXISTS (SELECT 1 FROM bookings b JOIN slots held ON b.slot_id = held.id WHERE b.status IN ('pending','confirmed') AND held.start < ? AND held.end > ?)`).bind(id,reference,slotId,name,email,phone,message,now,now,slotId,warsawNow(),slot.end,slot.start).run();}catch(error){if(/UNIQUE constraint/.test(String(error)))throw new HttpError(409,'This slot was just requested. Please choose another.');throw error;}if(!result.meta.changes)throw new HttpError(409,'This slot is no longer available. Please choose another.');return json({reference,status:'pending',start:slot.start,end:slot.end,service:slot.service},201);}
async function assistant(request,db){await throttle(request,db,'chat',40);const input=await body(request,3000),question=clean(input.message,500).toLowerCase(),en=input.language==='en',c=await config(db);if(!question)throw new HttpError(400,'Enter a question.');const choose=(pl,enText)=>en?enText:pl;let reply,action=null;if(/price|pricing|cena|ceny|cennik|koszt/.test(question)){reply=choose(`Wynajem: ${c.rentalPrice||'cena do potwierdzenia'}. Sesja: ${c.sessionPrice||'cena do potwierdzenia'}. Opisz projekt w formularzu rezerwacji.`,`Rental: ${c.rentalPrice||'price to be confirmed'}. Session: ${c.sessionPrice||'price to be confirmed'}. Describe your project in the booking form.`);action='booking';}else if(/equipment|sprzęt|sprzet|wyposaż|wyposaz|light|świat|swiat/.test(question)){reply=en?c.equipmentEn:c.equipmentPl;}else if(/adres|address|where|gdzie|lokal/.test(question)){reply=c.address?choose('Znajdziesz nas tutaj: ','Find us at: ')+c.address:choose('Studio działa w Warszawie. Dokładny adres potwierdź z zespołem przed wizytą.','The studio is in Warsaw. Confirm the exact address with the team before visiting.');}else if(/cancel|anul|zasad|policy|regulamin/.test(question)){reply=en?c.policyEn:c.policyPl;}else if(/book|termin|rezerw|date|wynaj|rental|avail|dostęp/.test(question)){const slots=await available(db);reply=slots.length?choose(`Aktualnie możesz zapytać o ${slots.length} terminów. Najbliższy: ${slots[0].start.replace('T',' ')} (czas warszawski). Wybierz termin w formularzu; zespół potwierdzi rezerwację.`,`There are ${slots.length} slots available to request. Next: ${slots[0].start.replace('T',' ')} (Warsaw time). Select a slot in the form; the studio will confirm your booking.`):choose('Studio nie opublikowało jeszcze dostępnych terminów. Napisz do nas na Instagramie, aby zapytać o swój projekt.','The studio has not published available slots yet. Message us on Instagram about your project.');action=slots.length?'booking':'instagram';}else if(/sesj|session|portret|portrait|fotograf/.test(question)){reply=choose('Wybierz sesję z fotografem, termin i opisz zdjęcia, które chcesz stworzyć. Zapiszemy zapytanie, a studio potwierdzi szczegóły.','Choose a photography session and a slot, then describe the images you want to create. Your request will be saved for the studio to review.');action='booking';}else{reply=choose('Pomogę z dostępnością, cenami, wyposażeniem i zasadami rezerwacji. W sprawie niestandardowego projektu porozmawiaj z zespołem na Instagramie.','I can help with availability, pricing, equipment, and booking terms. For a custom project, contact the team on Instagram.');action='instagram';}return json({reply,action,kind:'studio-faq'});}
async function uploadPhoto(request,env,db){if(!env.BUCKET)throw new HttpError(503,'Photo storage temporarily unavailable.');const bytes=await readLimited(request,10*1024*1024);let type,extension;if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff){type='image/jpeg';extension='jpg';}else if(bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10'){type='image/png';extension='png';}else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP'){type='image/webp';extension='webp';}else throw new HttpError(400,'Use a JPEG, PNG or WebP image (maximum 10 MB).');const url=new URL(request.url),category=url.searchParams.get('category');if(!['studio','session'].includes(category))throw new HttpError(400,'Choose a photo category.');const pl=clean(url.searchParams.get('captionPl'),200),en=clean(url.searchParams.get('captionEn'),200);if(!pl||!en)throw new HttpError(400,'Enter both photo captions.');const id=crypto.randomUUID(),key=`photos/${id}.${extension}`;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type}});try{await db.prepare('INSERT INTO photos (id, object_key, category, caption_pl, caption_en, position, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(id,key,category,pl,en,Date.now(),new Date().toISOString()).run();}catch(error){await env.BUCKET.delete(key);throw error;}return json({id,url:'/media/'+id},201);}
async function adminAPI(request,env,db,url){requireAdmin(request,env);const path=url.pathname;if(path==='/api/admin/dashboard'&&request.method==='GET'){const results=await db.batch([db.prepare('SELECT b.*, s.service, s.start, s.end FROM bookings b JOIN slots s ON s.id = b.slot_id ORDER BY b.created_at DESC LIMIT 500'),db.prepare('SELECT s.*, (SELECT b.status FROM bookings b WHERE b.slot_id = s.id AND b.status IN (\'pending\',\'confirmed\') LIMIT 1) AS booking_status FROM slots s ORDER BY s.start DESC LIMIT 500'),db.prepare('SELECT id, category, caption_pl, caption_en, position FROM photos ORDER BY position')]);return json({bookings:results[0].results,slots:results[1].results,photos:results[2].results,settings:await config(db),admin:identity(request,env)});}
 if(request.method!=='GET')requireSameOrigin(request);
 if(path==='/api/admin/settings'&&request.method==='PUT'){const c=normalizeSettings(await body(request,30000));for(const key of ['heroPhoto','studioPhoto']){if(c[key]&&!await db.prepare('SELECT id FROM photos WHERE id = ?').bind(c[key]).first())throw new HttpError(400,'Selected photo does not exist.');}await db.prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('studio',JSON.stringify(c)).run();return json({saved:true});}
 if(path==='/api/admin/slots'&&request.method==='POST'){const input=await body(request);if(!['studio','session'].includes(input.service)||!validDateTime(input.start)||!validDateTime(input.end)||input.start<=warsawNow()||input.end<=input.start||input.end.slice(0,10)!==input.start.slice(0,10))throw new HttpError(400,'Choose a valid future slot within a single day (Warsaw time).');const id=crypto.randomUUID();const result=await db.prepare(`INSERT INTO slots (id,service,start,end,state,created_at) SELECT ?,?,?,?,'open',? WHERE NOT EXISTS (SELECT 1 FROM slots WHERE state = 'open' AND start < ? AND end > ?)`).bind(id,input.service,input.start,input.end,new Date().toISOString(),input.end,input.start).run();if(!result.meta.changes)throw new HttpError(409,'This slot overlaps an existing open slot.');return json({id},201);}
 const slotMatch=path.match(/^\/api\/admin\/slots\/([\w-]+)$/);if(slotMatch&&request.method==='PATCH'){const input=await body(request);if(!['open','blocked'].includes(input.state))throw new HttpError(400,'Invalid slot state.');const slot=await db.prepare('SELECT * FROM slots WHERE id = ?').bind(slotMatch[1]).first();if(!slot)throw new HttpError(404,'Slot not found.');if(input.state==='blocked'&&await db.prepare("SELECT id FROM bookings WHERE slot_id = ? AND status IN ('pending','confirmed')").bind(slot.id).first())throw new HttpError(409,'Cancel or decline the booking before blocking its slot.');const result=await db.prepare(`UPDATE slots SET state = ? WHERE id = ? AND NOT EXISTS (SELECT 1 FROM bookings WHERE slot_id = ? AND status IN ('pending','confirmed')) AND (? = 'blocked' OR NOT EXISTS (SELECT 1 FROM slots other WHERE other.id <> ? AND other.state = 'open' AND other.start < ? AND other.end > ?))`).bind(input.state,slot.id,slot.id,input.state,slot.id,slot.end,slot.start).run();if(!result.meta.changes)throw new HttpError(409,'Slot overlaps another open slot.');return json({saved:true});}
 const match=path.match(/^\/api\/admin\/bookings\/([\w-]+)$/);if(match&&request.method==='PATCH'){const input=await body(request);if(!bookingStates.has(input.status)||input.status==='pending')throw new HttpError(400,'Invalid booking status.');const booking=await db.prepare('SELECT * FROM bookings WHERE id = ?').bind(match[1]).first();if(!booking)throw new HttpError(404,'Booking not found.');if(!['pending','confirmed'].includes(booking.status))throw new HttpError(409,'This booking is already closed.');const updated=await db.prepare("UPDATE bookings SET status = ?, updated_at = ? WHERE id = ? AND status IN ('pending','confirmed')").bind(input.status,new Date().toISOString(),booking.id).run();if(!updated.meta.changes)throw new HttpError(409,'This booking is already closed.');return json({saved:true});}
 if(path==='/api/admin/photos'&&request.method==='POST')return uploadPhoto(request,env,db);
 const photoMatch=path.match(/^\/api\/admin\/photos\/([\w-]+)$/);if(photoMatch&&request.method==='DELETE'){if(!env.BUCKET)throw new HttpError(503,'Photo storage unavailable.');const photo=await db.prepare('SELECT * FROM photos WHERE id = ?').bind(photoMatch[1]).first();if(!photo)throw new HttpError(404,'Photo not found.');const c=await config(db);if(c.heroPhoto===photo.id)c.heroPhoto='';if(c.studioPhoto===photo.id)c.studioPhoto='';await db.batch([db.prepare('DELETE FROM photos WHERE id = ?').bind(photo.id),db.prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('studio',JSON.stringify(c))]);await env.BUCKET.delete(photo.object_key);return json({deleted:true});}
 throw new HttpError(404,'Endpoint not found.');}
export async function handle(request,env){const url=new URL(request.url),path=url.pathname;if(path.startsWith('/api/')){const db=requireDB(env);if(path.startsWith('/api/admin/'))return adminAPI(request,env,db,url);if(path==='/api/studio'&&request.method==='GET'){const photos=(await db.prepare('SELECT id, category, caption_pl, caption_en FROM photos ORDER BY position').all()).results;return json({settings:await config(db),photos,timezone:'Europe/Warsaw'});}if(path==='/api/availability'&&request.method==='GET'){const service=url.searchParams.get('service')||'',date=url.searchParams.get('date')||'';if(service&&!['studio','session'].includes(service))throw new HttpError(400,'Invalid service.');if(date&&!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new HttpError(400,'Invalid date.');return json({slots:await available(db,service,date),timezone:'Europe/Warsaw'});}if(path==='/api/bookings'&&request.method==='POST'){requireSameOrigin(request);return createBooking(request,db);}if(path==='/api/chat'&&request.method==='POST'){requireSameOrigin(request);return assistant(request,db);}throw new HttpError(404,'Endpoint not found.');}
 const media=path.match(/^\/media\/([\w-]+)$/);if(media&&request.method==='GET'){const db=requireDB(env);const photo=await db.prepare('SELECT object_key FROM photos WHERE id = ?').bind(media[1]).first();if(!photo||!env.BUCKET)return new Response('Not found',{status:404});const object=await env.BUCKET.get(photo.object_key);if(!object)return new Response('Not found',{status:404});return new Response(object.body,{headers:{...securityHeaders,'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=86400',ETag:object.httpEtag}});}
 if(path==='/admin'||path==='/admin/'){if(!identity(request,env))return Response.redirect(url.origin+'/signin-with-chatgpt?return_to=%2Fadmin',302);if(!isAdmin(request,env))return new Response('Administrator access required.',{status:403,headers:securityHeaders});return new Response(ASSETS['/admin.html'].body,{headers:{...securityHeaders,'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});}
 const asset=ASSETS[path==='/'?'/index.html':path];if(asset&&path!=='/admin.html')return new Response(request.method==='HEAD'?null:asset.body,{headers:{...securityHeaders,'Content-Type':asset.type,'Cache-Control':'no-cache'}});return new Response('Not found',{status:404,headers:securityHeaders});}
export default {async fetch(request,env){try{return await handle(request,env);}catch(error){if(!(error instanceof HttpError))console.error('Aura request failed',error);return json({error:error instanceof HttpError?error.message:'Studio service temporarily unavailable. Please try again.'},error instanceof HttpError?error.status:503);}}};
